AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stack:
    Type: String
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  Tag:
    Type: String
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref AWS::StackName
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: liquidity
          Image:
            !Sub "837036139524.dkr.ecr.eu-west-2.amazonaws.com/liquidity:${Tag}"
          ReadonlyRootFilesystem: true
          Memory: 384
          PortMappings:
          - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue: !Sub "${Stack}-CloudWatchLogGroup"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: liquidity
          Environment:
            - Name: AKKA_HOSTNAME
              Value: "localhost"
            - Name: JAVA_OPTS
              Value: "-Dakka.cluster.seed-nodes.0=\
                akka.tcp://liquidity@localhost:2552
                -Dakka.cluster.roles.0=zone-host
                -Dakka.cluster.roles.1=client-relay
                -Dakka.cluster.roles.2=analytics"
            - Name: MYSQL_HOSTNAME
              Value:
                Fn::ImportValue: !Sub "${Stack}-RDSHostname"
            - Name: MYSQL_USERNAME
              Value:
                Fn::ImportValue: !Sub "${Stack}-RDSUsername"
            - Name: MYSQL_PASSWORD
              Value:
                Fn::ImportValue: !Sub "${Stack}-RDSPassword"
  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${AWS::StackName}-service"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub "${Stack}-ALBSecurityGroup"
  Service:
    Type: AWS::ECS::Service
    Properties:
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !GetAtt ServiceSecurityGroup.GroupId
          Subnets: !Ref Subnets
      ServiceName: !Ref AWS::StackName
      DesiredCount: 1
      DeploymentConfiguration:
        MinimumHealthyPercent: 0
        MaximumPercent: 100
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: liquidity
          ContainerPort: 8080
          TargetGroupArn:
            Fn::ImportValue: !Sub "${Stack}-ALBTargetGroup"
