version: '2'
services:
  cassandra:
    image: cassandra:3
    restart: always
    volumes:
    - cassandra-data:/var/lib/cassandra
  server:
    build: server
    ports:
     - '443:443'
    restart: always
    links:
      - cassandra
  analytics:
    build: analytics
    links:
      - cassandra
volumes:
  cassandra-data:
