version: '3'
services:
  zone-host:
    build: server
    restart: always
    extra_hosts:
      - "zone-host:127.0.0.1"
    environment:
      AKKA_HOSTNAME: zone-host
      JAVA_OPTS: >
        -Dakka.cluster.roles.0=zone-host
        -Dakka.cluster.seed-nodes.0=akka.tcp://liquidity@zone-host:2552
  client-relay:
    build: server
    ports:
     - '80:80'
    restart: always
    extra_hosts:
      - "client-relay:127.0.0.1"
    environment:
      AKKA_HOSTNAME: client-relay
      JAVA_OPTS: >
        -Dakka.cluster.roles.0=client-relay
        -Dakka.cluster.seed-nodes.0=akka.tcp://liquidity@zone-host:2552
    depends_on:
      - zone-host
  analytics:
    build: server
    restart: always
    extra_hosts:
      - "analytics:127.0.0.1"
    environment:
      AKKA_HOSTNAME: analytics
      JAVA_OPTS: >
        -Dakka.cluster.roles.0=analytics
        -Dakka.cluster.seed-nodes.0=akka.tcp://liquidity@zone-host:2552
    depends_on:
      - zone-host
