version: '3'
services:
  cassandra:
    image: cassandra:3
    restart: always
    volumes:
    - cassandra-data:/var/lib/cassandra
  mysql:
    image: mysql:8
    restart: always
    volumes:
    - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  zone-host-seed:
    build: server
    restart: always
    extra_hosts:
      - "zone-host-seed:127.0.0.1"
    environment:
      AKKA_HOSTNAME: zone-host-seed
      JAVA_OPTS: >
        -Dakka.cluster.roles.0=zone-host
        -Dakka.cluster.seed-nodes.0=akka.tcp://liquidity@zone-host-seed:2552
    links:
      - cassandra
  analytics-seed:
    build: server
    restart: always
    extra_hosts:
      - "analytics-seed:127.0.0.1"
    environment:
      AKKA_HOSTNAME: analytics-seed
      JAVA_OPTS: >
        -Dakka.cluster.roles.0=analytics
        -Dakka.cluster.seed-nodes.0=akka.tcp://liquidity@zone-host-seed:2552
    links:
      - cassandra
      - mysql
      - zone-host-seed
  client-relay-seed:
    build: server
    ports:
     - '80:80'
    restart: always
    extra_hosts:
      - "client-relay-seed:127.0.0.1"
    environment:
      AKKA_HOSTNAME: client-relay-seed
      JAVA_OPTS: >
        -Dakka.cluster.roles.0=client-relay
        -Dakka.cluster.seed-nodes.0=akka.tcp://liquidity@zone-host-seed:2552
    links:
      - cassandra
      - zone-host-seed
volumes:
  cassandra-data:
  mysql-data:
