version: '2'
services:
  cassandra:
    image: cassandra:3.4
    restart: always
    volumes:
    - cassandra-data:/var/lib/cassandra
  liquidity:
    build: liquidity
    image: dhpcs/liquidity.dhpcs.com
    restart: always
    links:
      - cassandra
  nginx:
    build: nginx
    image: dhpcs/liquidity.dhpcs.com-nginx
    ports:
     - '443:443'
    restart: always
    links:
      - liquidity
volumes:
  cassandra-data:
