version: '3'
services:
  liquidity:
    build: server
    ports:
     - '80:80'
    restart: always
    extra_hosts:
      - "liquidity:127.0.0.1"
    environment:
      AKKA_HOSTNAME: liquidity
      JAVA_OPTS: >
        -Dakka.cluster.roles.0=zone-host
        -Dakka.cluster.roles.1=client-relay
        -Dakka.cluster.roles.2=analytics
        -Dakka.cluster.seed-nodes.0=akka.tcp://liquidity@liquidity:2552
      MYSQL_JOURNAL_URL: "jdbc:mysql://liquidity.cbn7pwslcac6.eu-west-2.rds.amazonaws.com/liquidity_journal?useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true&useLocalSessionState=true&useServerPrepStmts=true"
      MYSQL_JOURNAL_USERNAME: "liquidity"
      MYSQL_JOURNAL_PASSWORD: "liquidity"
      MYSQL_ANALYTICS_URL: "jdbc:mysql://liquidity.cbn7pwslcac6.eu-west-2.rds.amazonaws.com/liquidity_analytics?useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true&useLocalSessionState=true&useServerPrepStmts=true"
      MYSQL_ANALYTICS_USERNAME: "liquidity"
      MYSQL_ANALYTICS_PASSWORD: "liquidity"
    logging:
      driver: awslogs
      options:
        awslogs-group: liquidity
        awslogs-stream: liquidity
