version: '3'
services:
  zone-host:
    environment:
      MYSQL_JOURNAL_URL: "jdbc:mysql://liquidity.cbn7pwslcac6.eu-west-2.rds.amazonaws.com/liquidity_journal?useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true&useLocalSessionState=true&useServerPrepStmts=true"
      MYSQL_JOURNAL_USERNAME: "liquidity"
      MYSQL_JOURNAL_PASSWORD: "liquidity"
      MYSQL_ANALYTICS_URL: "jdbc:mysql://liquidity.cbn7pwslcac6.eu-west-2.rds.amazonaws.com/liquidity_analytics?useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true&useLocalSessionState=true&useServerPrepStmts=true"
      MYSQL_ANALYTICS_USERNAME: "liquidity"
      MYSQL_ANALYTICS_PASSWORD: "liquidity"
    logging:
      driver: awslogs
      options:
        awslogs-group: liquidity
        awslogs-stream: zone-host
  client-relay:
    environment:
      MYSQL_JOURNAL_URL: "jdbc:mysql://liquidity.cbn7pwslcac6.eu-west-2.rds.amazonaws.com/liquidity_journal?useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true&useLocalSessionState=true&useServerPrepStmts=true"
      MYSQL_JOURNAL_USERNAME: "liquidity"
      MYSQL_JOURNAL_PASSWORD: "liquidity"
      MYSQL_ANALYTICS_URL: "jdbc:mysql://liquidity.cbn7pwslcac6.eu-west-2.rds.amazonaws.com/liquidity_analytics?useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true&useLocalSessionState=true&useServerPrepStmts=true"
      MYSQL_ANALYTICS_USERNAME: "liquidity"
      MYSQL_ANALYTICS_PASSWORD: "liquidity"
    logging:
      driver: awslogs
      options:
        awslogs-group: liquidity
        awslogs-stream: client-relay
  analytics:
    environment:
      MYSQL_JOURNAL_URL: "jdbc:mysql://liquidity.cbn7pwslcac6.eu-west-2.rds.amazonaws.com/liquidity_journal?useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true&useLocalSessionState=true&useServerPrepStmts=true"
      MYSQL_JOURNAL_USERNAME: "liquidity"
      MYSQL_JOURNAL_PASSWORD: "liquidity"
      MYSQL_ANALYTICS_URL: "jdbc:mysql://liquidity.cbn7pwslcac6.eu-west-2.rds.amazonaws.com/liquidity_analytics?useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true&useLocalSessionState=true&useServerPrepStmts=true"
      MYSQL_ANALYTICS_USERNAME: "liquidity"
      MYSQL_ANALYTICS_PASSWORD: "liquidity"
    logging:
      driver: awslogs
      options:
        awslogs-group: liquidity
        awslogs-stream: analytics
