version: '3'
services:
  mysql:
    image: mysql:5
    ports:
     - '3306'
    command: ["--explicit_defaults_for_timestamp=true"]
    volumes:
    - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  zone-host:
    image: "837036139524.dkr.ecr.eu-west-2.amazonaws.com/liquidity:${TAG}"
    ports:
     - '19999'
    extra_hosts:
      - "zone-host:127.0.0.1"
    environment:
      AKKA_HOSTNAME: zone-host
      JAVA_OPTS: >
        -Dakka.cluster.roles.0=zone-host
        -Dakka.cluster.seed-nodes.0=akka.tcp://liquidity@zone-host:2552
      MYSQL_JOURNAL_URL: "jdbc:mysql://mysql/liquidity_journal?useSSL=false&
        cacheCallableStmts=true&cachePrepStmts=true&
        cacheResultSetMetadata=true&cacheServerConfiguration=true&
        useLocalSessionState=true&useLocalSessionState=true&
        useServerPrepStmts=true"
      MYSQL_JOURNAL_USERNAME: "root"
      MYSQL_JOURNAL_PASSWORD: ""
      MYSQL_ANALYTICS_URL: "jdbc:mysql://mysql/liquidity_analytics?
        useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&
        cacheResultSetMetadata=true&cacheServerConfiguration=true&
        useLocalSessionState=true&useLocalSessionState=true&
        useServerPrepStmts=true"
      MYSQL_ANALYTICS_USERNAME: "root"
      MYSQL_ANALYTICS_PASSWORD: ""
    depends_on:
      - mysql
  client-relay:
    image: "837036139524.dkr.ecr.eu-west-2.amazonaws.com/liquidity:${TAG}"
    ports:
     - '19999'
     - '8080'
    extra_hosts:
      - "client-relay:127.0.0.1"
    environment:
      AKKA_HOSTNAME: client-relay
      JAVA_OPTS: >
        -Dakka.cluster.roles.0=client-relay
        -Dakka.cluster.seed-nodes.0=akka.tcp://liquidity@zone-host:2552
      MYSQL_JOURNAL_URL: "jdbc:mysql://mysql/liquidity_journal?useSSL=false&
        cacheCallableStmts=true&cachePrepStmts=true&
        cacheResultSetMetadata=true&cacheServerConfiguration=true&
        useLocalSessionState=true&useLocalSessionState=true&
        useServerPrepStmts=true"
      MYSQL_JOURNAL_USERNAME: "root"
      MYSQL_JOURNAL_PASSWORD: ""
      MYSQL_ANALYTICS_URL: "jdbc:mysql://mysql/liquidity_analytics?
        useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&
        cacheResultSetMetadata=true&cacheServerConfiguration=true&
        useLocalSessionState=true&useLocalSessionState=true&
        useServerPrepStmts=true"
      MYSQL_ANALYTICS_USERNAME: "root"
      MYSQL_ANALYTICS_PASSWORD: ""
    depends_on:
      - mysql
      - zone-host
  analytics:
    image: "837036139524.dkr.ecr.eu-west-2.amazonaws.com/liquidity:${TAG}"
    ports:
     - '19999'
    extra_hosts:
      - "analytics:127.0.0.1"
    environment:
      AKKA_HOSTNAME: analytics
      JAVA_OPTS: >
        -Dakka.cluster.roles.0=analytics
        -Dakka.cluster.seed-nodes.0=akka.tcp://liquidity@zone-host:2552
      MYSQL_JOURNAL_URL: "jdbc:mysql://mysql/liquidity_journal?useSSL=false&
        cacheCallableStmts=true&cachePrepStmts=true&
        cacheResultSetMetadata=true&cacheServerConfiguration=true&
        useLocalSessionState=true&useLocalSessionState=true&
        useServerPrepStmts=true"
      MYSQL_JOURNAL_USERNAME: "root"
      MYSQL_JOURNAL_PASSWORD: ""
      MYSQL_ANALYTICS_URL: "jdbc:mysql://mysql/liquidity_analytics?
        useSSL=false&cacheCallableStmts=true&cachePrepStmts=true&
        cacheResultSetMetadata=true&cacheServerConfiguration=true&
        useLocalSessionState=true&useLocalSessionState=true&
        useServerPrepStmts=true"
      MYSQL_ANALYTICS_USERNAME: "root"
      MYSQL_ANALYTICS_PASSWORD: ""
    depends_on:
      - mysql
      - zone-host
volumes:
  mysql-data:
