version: '2'
services:
  cassandra:
    image: cassandra:3
    restart: always
    volumes:
    - cassandra-data:/var/lib/cassandra
  akka-cluster:
    build: akka-cluster
  server:
    build: server
    ports:
     - '443:443'
    restart: always
    environment:
      JAVA_OPTS: >
        -Dcom.sun.management.jmxremote.port=9999
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
    links:
      - cassandra
  analytics:
    build: analytics
    restart: always
    links:
      - cassandra
volumes:
  cassandra-data:
