version: '2'
services:
  cassandra:
    image: cassandra:3
    restart: always
    volumes:
    - cassandra-data:/var/lib/cassandra
  liquidity:
    build: liquidity
    image: dhpcs/liquidity.dhpcs.com
    ports:
     - '443:443'
    restart: always
    links:
      - cassandra
volumes:
  cassandra-data:
