version: '3'
services:
  mysql:
    image: "mysql:5"
    ports:
     - "3306"
    command: [
      "--character-set-client-handshake=false",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--explicit-defaults-for-timestamp=true"
    ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  zone-host:
    image: "liquidity:${TAG}"
    ports:
     - "8080"
    environment:
      JAVA_OPTS: "-Dakka.remote.artery.canonical.hostname=zone-host
        -Dakka.management.http.hostname=zone-host
        -Dakka.discovery.method=hardcoded
        -Dakka.discovery.hardcoded.hostnames.0=zone-host
        -Dakka.discovery.hardcoded.hostnames.1=client-relay
        -Dakka.discovery.hardcoded.hostnames.2=analytics
        -Dakka.management.cluster.bootstrap.contact-point-discovery.\
         required-contact-point-nr=3
        -Dakka.cluster.roles.0=zone-host"
      MYSQL_HOSTNAME: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
  client-relay:
    image: "liquidity:${TAG}"
    ports:
     - "8080"
    environment:
      JAVA_OPTS: "-Dakka.remote.artery.canonical.hostname=client-relay
        -Dakka.management.http.hostname=client-relay
        -Dakka.discovery.method=hardcoded
        -Dakka.discovery.hardcoded.hostnames.0=zone-host
        -Dakka.discovery.hardcoded.hostnames.1=client-relay
        -Dakka.discovery.hardcoded.hostnames.2=analytics
        -Dakka.management.cluster.bootstrap.contact-point-discovery.\
         required-contact-point-nr=3
        -Dakka.cluster.roles.0=client-relay"
      MYSQL_HOSTNAME: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
  analytics:
    image: "liquidity:${TAG}"
    ports:
     - "8080"
    environment:
      JAVA_OPTS: "-Dakka.remote.artery.canonical.hostname=analytics
        -Dakka.management.http.hostname=analytics
        -Dakka.discovery.method=hardcoded
        -Dakka.discovery.hardcoded.hostnames.0=zone-host
        -Dakka.discovery.hardcoded.hostnames.1=client-relay
        -Dakka.discovery.hardcoded.hostnames.2=analytics
        -Dakka.management.cluster.bootstrap.contact-point-discovery.\
         required-contact-point-nr=3
        -Dakka.cluster.roles.0=analytics"
      MYSQL_HOSTNAME: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
