version: '3'
services:
  mysql:
    image: "mysql:5"
    ports:
     - "3306"
    command: [
      "--character-set-client-handshake=false",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--explicit-defaults-for-timestamp=true"
    ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  zone-host:
    image: "837036139524.dkr.ecr.us-east-1.amazonaws.com/liquidity:${TAG}"
    ports:
     - "8080"
    environment:
      JAVA_OPTS: "-Dakka.remote.artery.canonical.hostname=zone-host
        -Dakka.remote.artery.bind.hostname=0.0.0.0
        -Dakka.cluster.seed-nodes.0=akka://liquidity@zone-host:25520
        -Dakka.cluster.roles.0=zone-host"
      MYSQL_HOSTNAME: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
  client-relay:
    image: "837036139524.dkr.ecr.us-east-1.amazonaws.com/liquidity:${TAG}"
    ports:
     - "8080"
    environment:
      JAVA_OPTS: "-Dakka.remote.artery.canonical.hostname=client-relay
        -Dakka.remote.artery.bind.hostname=0.0.0.0
        -Dakka.cluster.seed-nodes.0=akka://liquidity@zone-host:25520
        -Dakka.cluster.roles.0=client-relay"
      MYSQL_HOSTNAME: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
  analytics:
    image: "837036139524.dkr.ecr.us-east-1.amazonaws.com/liquidity:${TAG}"
    ports:
     - "8080"
    environment:
      JAVA_OPTS: "-Dakka.remote.artery.canonical.hostname=analytics
        -Dakka.remote.artery.bind.hostname=0.0.0.0
        -Dakka.cluster.seed-nodes.0=akka://liquidity@zone-host:25520
        -Dakka.cluster.roles.0=analytics"
      MYSQL_HOSTNAME: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
